### ISSUE TITLE
Extension remains as .coffee in Jekyll 3.1.x

### ISSUE THREAD

**Issue by wjdp** [jekyll/jekyll-coffeescript#15]
I'm upgrading our site to Jekyll 3.1.x ( https://github.com/newtheatre/history-project/pull/496 ) and seeing coffeescript files that compile but their extensions do not change. Two files here, lib.js is unrelated.

![image](https://cloud.githubusercontent.com/assets/1690934/13642148/37bf560e-e613-11e5-8165-1d64da44e70d.png)

![image](https://cloud.githubusercontent.com/assets/1690934/13642166/4897e3d8-e613-11e5-8c16-380665b268d6.png)

I see no change in jekyll-coffeescript and no other reports so could very well be something dodgy in our repo.

**Comment by wjdp** [comment]
Whoops, seems on futher inspection to be an issue with jekyll-jsminify. Correct behaviour when it's omitted.

**Comment by stephenyeargin** [comment]
If anyone else comes across this, my solution was to ensure that `jekyll-coffee` is properly loaded in my `_config.yml` file under the `gems:` key.

```yml
gems:
  - jekyll-coffeescript
```
