### ISSUE TITLE
Circular dependence with jekyll:2.5.3

### ISSUE THREAD

**Issue by pinikeizman** [jekyll/jekyll-coffeescript#34]
Hi, we are using jekyll:2.5.3 on some legacy doc static site and we encountered a circular dependence while installing jekyll:2.5.3
This is due to this file changed yesterday:
https://github.com/jekyll/jekyll-coffeescript/blob/b2322d7020905eefff1eb795bd1cf20c2c5ab161/Gemfile#L6
If we could evaluate this if statement to false I think this will fix the circular dependence issue, but it will always evaluate to true because ruby can't eval string to false in if statement.
Would you mind to enhance this code so we could evaluate it to false some how?
Maybe check for "false" string and skip the gem command.

**Comment by ashmaroli** [comment]
That change affects only the development of `jekyll-coffeescript` not its usage.
Is the *legacy site* available as a public repository?

**Comment by pinikeizman** [comment]
Thanks for the quick reply, the repo is public and can be viewed here:
https://github.com/bigpandaio/docs.bigpanda.io
I'm new to ruby so I might be wrong, but the build worked 2 days ago and it fails now.

**Comment by ashmaroli** [comment]
Actually, you're right. Jekyll 2.5.3 has `jekyll-coffeescript` as a runtime_dependency which **now** has jekyll as a runtime_dependency as well.
I'll push a new version a.s.a.p.

**Comment by pinikeizman** [comment]
Thanks!

**Comment by ashmaroli** [comment]
I've pushed a new version. This should be resolved now.
Please check and close.
Thank you for reporting.

**Comment by pinikeizman** [comment]
Thanks, the issue has been fixed.
